site_name: EXCO Resources Ignition 8.1 System Guide
repo_url: https://github.com/Mokrecho1/ER-8.1SystemDocumentation

copyright: Proprietary information, for the express use of TIGA, A Tetra Tech Company

theme:
   name: material
   features:
      - search.suggest
      - search.highlight
      - content.tabs.link
      - content.code.annotation
      - content.code.copy
   language: en
   palette:
      scheme: 
      primary: green

nav:
  - index.md
  - Header Filter Navigation.md
  - User Settings.md
  - Navigation.md
  - Dashboard Screen.md
  - Production Overview Screen.md
  - Production Detail Screen.md
  - Central Facility Screen.md
  - Comms Overview Screen.md
  - Reports Screen.md
  - VO Tickets Screen.md
  - Alarm Overview Screen.md
  - Metadata Editor Screen.md
  - Alarm Tier Screen.md
  - Deliverability Screen.md

Extra:
   social:
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/company/the-integration-group-of-americas-inc
   
markdown_extensions:
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
